version: '3'

services:
  plex:
    image: plexinc/pms-docker
    network_mode: host
    env_file: plex.env
    volumes:
      - ./plex/confif:/config
      - ./plex/transcode:/transcode
      - ./plex/data:/data

  zoneminder:
    image: linuxserver/zoneminder
    ports:
      - "81:80"

  kodi:
    image: linuxserver/kodi-headless
    volumes:
      - ./kodi:/config
    env_file: kodi.env
    ports:
      - "82:8080"
      - "9090:9090"
      - "9777:9777/udp"

  home-assistant:
    image: homeassistant/home-assistant
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    env_file: home-assistant.env
    network_mode: host
    ports:
      - "83:8123"
