version: '3'

services:
  plex:
    image: plexinc/pms-docker
    network_mode: host
    env_file: plex.env
    volumes:
      - ./plex/confif:/config
      - ./plex/transcode:/transcode
      - ./plex/data:/data

  zoneminder:
    image: linuxserver/zoneminder
    ports:
      - "81:80"

  kodi:
    image: linuxserver/kodi-headless
    volumes:
      - ./kodi:/config
    env_file: kodi.env
    ports:
      - "82:8080"
      - "9090:9090"
      - "9777:9777/udp"

#  memcached:
#    container_name: dev_memcached_1
#    image: memcached
#    restart: always
#    ports:
#      - "3306:3306"
#
